"""The validity harness: does a hand-written world reproduce the eval outcome the system it
replicates produces, and does it rank agent configurations the same way?

This package is the generic half. It holds the measurement — replaying recorded tool calls
against the world, replaying recorded decisions with the world's results substituted, the
paired and rank statistics, the gates, the seeded-fault loop, the cost model and the
report — and **nothing about any particular world**. No product vocabulary, no model ids,
no fixture names: the scrub rules, create tools, served tools, declared divergences, world
server command, fault table and pricing all arrive as arguments from a driver that knows
its own world. `test_package` greps the sources for the names this project would plausibly
leak; it is a tripwire, not a proof.

    rules = ScrubRules.from_file(config_path).with_declared(
        declared_from_evidence(evidence, tool_names)
    )
    episodes = load_episodes(task, eval_config, run_configs, ...)
    replayed = replay_all(world, "<fixture>", episodes, rules, ...)
    gates = evaluate_gates(mismatches=..., paired=..., scores=..., decisions=..., thresholds=...)
    write_report(build_report(meta, ...), out_dir)

The driver lives beside the world package it measures, and is the only place that names it.

One name is deliberately not re-exported: `scrub.scrub`, the function, would shadow
`scrub`, the module, and the module is what drivers and the boundary test reach for. Call
it as `scrub.scrub(value, rules)`.
"""

from __future__ import annotations

from . import (
    cost,
    decision,
    faults,
    idmap,
    metrics,
    replay,
    report,
    scrub,
    traces,
)
from .cost import BudgetExceeded, CostLine, CostMeter, CostModel, Pricing, estimate
from .decision import (
    Arm,
    Call,
    DecisionRecord,
    DecisionSelection,
    PrefixKind,
    RecordingSessionManager,
    StopReplay,
    build_prefix,
    divergent_prefix,
    load_records,
    replay_all_decisions,
    replay_decision,
    select_decisions,
)
from .faults import (
    FaultResult,
    FaultSpec,
    FaultTarget,
    TriggerCounter,
    WorldServer,
    WorldServerDown,
    WorldServerError,
    capacity_caveat,
    count_for,
    detect,
    evaluable,
    port_is_free,
    start_world_server,
    stop_world_server,
    trigger_count_in_process,
    watch_liveness,
)
from .idmap import IdMap, IdMapConflict, created_id
from .metrics import (
    Cell,
    ConfigScore,
    DecisionStat,
    DroppedPair,
    Gate,
    GateName,
    GateOutcome,
    GateResults,
    GateThresholds,
    Interval,
    NearNeighbour,
    PairedCell,
    PairedStat,
    RankStat,
    SanityCounts,
    agreement,
    average_ranks,
    bootstrap_episodes,
    bootstrap_inputs,
    cell_rates,
    cells,
    config_scores,
    decision_stat,
    delta_value,
    evaluate_gates,
    evaluate_gates_with_stats,
    fault_gate,
    fault_thresholds,
    moved_beyond_interval,
    moved_gates,
    near_neighbour,
    pair_cells,
    paired_delta,
    rank_stat,
    sanity_counts,
    spearman,
)
from .replay import (
    DivergenceClass,
    Mismatch,
    MismatchKind,
    ReplayedEpisode,
    argument_ids,
    replay_all,
    replay_episode,
    undeclared_classes,
)
from .report import (
    ALL_STEPS,
    DECISION_RULES,
    WHAT_THIS_DOES_NOT_PROVE,
    Deviation,
    RunMeta,
    Step,
    build_report,
    render_markdown,
    write_report,
)
from .scrub import (
    Declared,
    Diff,
    FieldClass,
    ScrubRules,
    compare,
    declared_from_evidence,
    is_declared,
    normalize_arguments,
    path_signature,
)
from .traces import (
    ConfigKey,
    Half,
    InvalidReason,
    PairKey,
    RecordedEpisode,
    System,
    ToolStep,
    changes,
    extract_steps,
    final_state,
    invalid_reason,
    load_episodes,
    settle_error,
    step_count,
    world_gap,
)

__all__ = [
    "ALL_STEPS",
    "DECISION_RULES",
    "WHAT_THIS_DOES_NOT_PROVE",
    "Arm",
    "BudgetExceeded",
    "Call",
    "Cell",
    "ConfigKey",
    "ConfigScore",
    "CostLine",
    "CostMeter",
    "CostModel",
    "DecisionRecord",
    "DecisionSelection",
    "DecisionStat",
    "Declared",
    "Deviation",
    "Diff",
    "DivergenceClass",
    "DroppedPair",
    "FaultResult",
    "FaultSpec",
    "FaultTarget",
    "FieldClass",
    "Gate",
    "GateName",
    "GateOutcome",
    "GateResults",
    "GateThresholds",
    "Half",
    "IdMap",
    "IdMapConflict",
    "Interval",
    "InvalidReason",
    "Mismatch",
    "MismatchKind",
    "NearNeighbour",
    "PairKey",
    "PairedCell",
    "PairedStat",
    "PrefixKind",
    "Pricing",
    "RankStat",
    "RecordedEpisode",
    "RecordingSessionManager",
    "ReplayedEpisode",
    "RunMeta",
    "SanityCounts",
    "ScrubRules",
    "Step",
    "StopReplay",
    "System",
    "ToolStep",
    "TriggerCounter",
    "WorldServer",
    "WorldServerDown",
    "WorldServerError",
    "agreement",
    "argument_ids",
    "average_ranks",
    "bootstrap_episodes",
    "bootstrap_inputs",
    "build_prefix",
    "build_report",
    "capacity_caveat",
    "cell_rates",
    "cells",
    "changes",
    "compare",
    "config_scores",
    "cost",
    "count_for",
    "created_id",
    "decision",
    "decision_stat",
    "declared_from_evidence",
    "delta_value",
    "detect",
    "divergent_prefix",
    "estimate",
    "evaluable",
    "evaluate_gates",
    "evaluate_gates_with_stats",
    "extract_steps",
    "fault_gate",
    "fault_thresholds",
    "faults",
    "final_state",
    "idmap",
    "invalid_reason",
    "is_declared",
    "load_episodes",
    "load_records",
    "metrics",
    "moved_beyond_interval",
    "moved_gates",
    "near_neighbour",
    "normalize_arguments",
    "pair_cells",
    "paired_delta",
    "path_signature",
    "port_is_free",
    "rank_stat",
    "render_markdown",
    "replay",
    "replay_all",
    "replay_all_decisions",
    "replay_decision",
    "replay_episode",
    "report",
    "sanity_counts",
    "scrub",
    "select_decisions",
    "settle_error",
    "spearman",
    "start_world_server",
    "step_count",
    "stop_world_server",
    "traces",
    "trigger_count_in_process",
    "undeclared_classes",
    "watch_liveness",
    "world_gap",
    "write_report",
]
