"""Shared builders for the harness tests: synthetic traces, a toy world to replay against,
and small constructors for the dataclasses the statistics consume.

The traces are built by hand rather than generated by an adapter, so a test can put a
trace in exactly the shape it wants to measure — a dangling tool call, a parallel batch,
an error envelope — without a model in the loop.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from kiln_ai.worlds.shim.ctx import Ctx
from kiln_ai.worlds.shim.errors import ToolError
from kiln_ai.worlds.shim.world import World

from .decision import Call, DecisionRecord
from .metrics import Cell, PairedCell
from .traces import RecordedEpisode, assistant_indices, extract_steps

FIXED_NOW = "2026-03-04T05:06:07.008Z"


# ---- traces ----


def system_message(text: str = "You are a helpful agent.") -> dict[str, Any]:
    return {"role": "system", "content": text}


def user_message(text: str = "Do the thing.") -> dict[str, Any]:
    return {"role": "user", "content": text}


def tool_call(call_id: str, name: str, **arguments: Any) -> dict[str, Any]:
    return {
        "id": call_id,
        "type": "function",
        "function": {"name": name, "arguments": json.dumps(arguments)},
    }


def assistant_message(
    *calls: dict[str, Any], content: str | None = None
) -> dict[str, Any]:
    message: dict[str, Any] = {"role": "assistant", "content": content}
    if calls:
        message["tool_calls"] = list(calls)
    return message


def tool_message(
    call_id: str, result: Any, *, is_error: bool | None = None, raw: str | None = None
) -> dict[str, Any]:
    return {
        "role": "tool",
        "tool_call_id": call_id,
        "content": raw if raw is not None else json.dumps(result),
        "is_error": is_error,
    }


def error_result(
    code: str, message: str = "nope", details: Any = None
) -> dict[str, Any]:
    return {"error": {"code": code, "message": message, "details": details}}


def trace(*messages: dict[str, Any]) -> list[Any]:
    return list(messages)


def episode(
    *messages: dict[str, Any],
    run_id: str = "run-1",
    configuration: str = "A",
    system: str = "real",
    repeat: int = 1,
    input_no: int = 1,
    half: str = "tuning",
    world_episode: dict[str, Any] | None = None,
    scores: dict[str, float] | None = None,
    invalid: Any = None,
    skipped_reason: str | None = None,
) -> RecordedEpisode:
    """A RecordedEpisode over a hand-built trace, with the steps extracted for real."""
    full: list[Any] = list(messages)
    return RecordedEpisode(
        run_id=run_id,
        eval_input_id=f"input-{input_no}",
        run_config_id=f"{configuration}-{system}-r{repeat}",
        configuration=configuration,
        system=system,  # type: ignore[arg-type]
        repeat=repeat,
        input_no=input_no,
        half=half,  # type: ignore[arg-type]
        trace=full,
        steps=extract_steps(full),
        assistant_indices=assistant_indices(full),
        final_message="done",
        world_episode=world_episode,
        scores=scores,
        skipped_reason=skipped_reason,
        invalid=invalid,
    )


# ---- a toy world ----

NOTES_SCHEMA = """
CREATE TABLE notes (
    id TEXT PRIMARY KEY,
    text TEXT NOT NULL,
    done INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    epoch INTEGER NOT NULL DEFAULT 0
) STRICT;
"""


def build_notes_world(tmp_path) -> World:
    """One table, five tools: create, read, list, finish and a delete that answers null."""
    world = World(
        "notes",
        version="1.0.0",
        schema=NOTES_SCHEMA,
        fixtures_dir=tmp_path / "fixtures",
        work_dir=tmp_path / "work",
    )

    def row(ctx: Ctx, note_id: str) -> dict[str, Any] | None:
        return ctx.db.one("SELECT * FROM notes WHERE id = ?", note_id)

    @world.tool
    def create_note(ctx: Ctx, text: str) -> dict:
        """Create a note."""
        note_id = ctx.ids.uuid()
        ctx.db.execute(
            "INSERT INTO notes (id, text, created_at, epoch) VALUES (?, ?, ?, 1)",
            note_id,
            text,
            ctx.clock.iso(),
        )
        created = row(ctx, note_id)
        assert created is not None
        return created

    @world.tool
    def get_note(ctx: Ctx, note_id: str) -> dict:
        """Read a note."""
        found = row(ctx, note_id)
        if found is None:
            raise ToolError("not_found", f"no note {note_id}", {"id": note_id})
        return found

    @world.tool
    def list_notes(ctx: Ctx) -> dict:
        """List every note."""
        rows = ctx.db.rows("SELECT * FROM notes ORDER BY id")
        return {"results": rows, "count": len(rows)}

    @world.tool
    def finish_note(ctx: Ctx, note_id: str) -> dict:
        """Mark a note done."""
        if not ctx.db.execute(
            "UPDATE notes SET done = 1 WHERE id = ?", note_id
        ).rowcount:
            raise ToolError("not_found", f"no note {note_id}", {"id": note_id})
        found = row(ctx, note_id)
        assert found is not None
        return found

    @world.tool
    def delete_note(ctx: Ctx, note_id: str) -> None:
        """Delete a note. Answers null, like a real DELETE with an empty body."""
        ctx.db.execute("DELETE FROM notes WHERE id = ?", note_id)
        return None

    return world


@pytest.fixture
def notes_world(tmp_path) -> World:
    return build_notes_world(tmp_path)


@pytest.fixture
def notes_fixture(notes_world: World) -> str:
    """A frozen fixture with one note, `n1`."""
    instance = notes_world.instance(None, now=FIXED_NOW)
    try:
        with instance.bulk() as ctx:
            ctx.db.execute(
                "INSERT INTO notes (id, text, created_at, epoch) "
                "VALUES ('n1', 'first', ?, 1)",
                FIXED_NOW,
            )
        instance.freeze("base", "one note")
    finally:
        instance.destroy()
    return "base"


@pytest.fixture
def served() -> frozenset[str]:
    return frozenset(
        {"create_note", "get_note", "list_notes", "finish_note", "delete_note"}
    )


# ---- metric inputs ----


def cell(
    configuration: str = "A",
    input_no: int = 1,
    repeat: int = 1,
    system: str = "real",
    *,
    passed: bool | None = True,
    invalid: Any = None,
    half: str = "tuning",
    steps: int | None = 3,
    scores: dict[str, float] | None = None,
) -> Cell:
    return Cell(
        configuration=configuration,
        input_no=input_no,
        repeat=repeat,
        system=system,  # type: ignore[arg-type]
        half=half,  # type: ignore[arg-type]
        run_id=None if invalid == "reset_anomaly" and passed is None else "run",
        passed=passed,
        invalid=invalid,
        steps=steps,
        scores=scores,
    )


def paired_cell(
    configuration: str = "A",
    input_no: int = 1,
    repeat: int = 1,
    *,
    real: bool = True,
    world: bool = True,
    half: str = "tuning",
) -> PairedCell:
    return PairedCell(
        configuration=configuration,
        input_no=input_no,
        repeat=repeat,
        half=half,  # type: ignore[arg-type]
        real=real,
        world=world,
    )


def decision_record(
    run_id: str = "run-1",
    decision_index: int = 0,
    arm: str = "world",
    *,
    prefix: str = "divergent",
    agree: bool = True,
    configuration: str = "A",
    error: str | None = None,
) -> DecisionRecord:
    return DecisionRecord(
        run_id=run_id,
        configuration=configuration,
        decision_index=decision_index,
        arm=arm,  # type: ignore[arg-type]
        prefix=prefix,  # type: ignore[arg-type]
        recorded=[Call("create_note", {"text": "string"})],
        replayed=[Call("create_note", {"text": "string"})],
        name_match=agree,
        args_match=agree,
        agree=agree,
        usage=None,
        error=error,
    )
