from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.data_source_type import DataSourceType
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.data_source_properties import DataSourceProperties
    from ..models.kiln_agent_run_config_properties import KilnAgentRunConfigProperties
    from ..models.mcp_run_config_properties import McpRunConfigProperties


T = TypeVar("T", bound="DataSource")


@_attrs_define
class DataSource:
    """Represents the origin of data, either human, synthetic, file import, or tool call, with associated properties.

    Properties vary based on the source type - for synthetic/tool_call sources this includes
    model information, for human sources this includes creator information, for file imports
    this includes file information.

        Attributes:
            type_ (DataSourceType): The source type of a piece of data.

                Human: a human created the data
                Synthetic: a model created the data
            properties (DataSourceProperties | Unset): Properties describing the data source. For synthetic things like
                model. For human: the human's name. For file_import: file information.
            run_config (KilnAgentRunConfigProperties | McpRunConfigProperties | None | Unset): The run config used to
                generate the data, if generated by a running a model in Kiln (only true for type=synthetic).
    """

    type_: DataSourceType
    properties: DataSourceProperties | Unset = UNSET
    run_config: KilnAgentRunConfigProperties | McpRunConfigProperties | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.kiln_agent_run_config_properties import KilnAgentRunConfigProperties
        from ..models.mcp_run_config_properties import McpRunConfigProperties

        type_ = self.type_.value

        properties: dict[str, Any] | Unset = UNSET
        if not isinstance(self.properties, Unset):
            properties = self.properties.to_dict()

        run_config: dict[str, Any] | None | Unset
        if isinstance(self.run_config, Unset):
            run_config = UNSET
        elif isinstance(self.run_config, KilnAgentRunConfigProperties):
            run_config = self.run_config.to_dict()
        elif isinstance(self.run_config, McpRunConfigProperties):
            run_config = self.run_config.to_dict()
        else:
            run_config = self.run_config

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "type": type_,
            }
        )
        if properties is not UNSET:
            field_dict["properties"] = properties
        if run_config is not UNSET:
            field_dict["run_config"] = run_config

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.data_source_properties import DataSourceProperties
        from ..models.kiln_agent_run_config_properties import KilnAgentRunConfigProperties
        from ..models.mcp_run_config_properties import McpRunConfigProperties

        d = dict(src_dict)
        type_ = DataSourceType(d.pop("type"))

        _properties = d.pop("properties", UNSET)
        properties: DataSourceProperties | Unset
        if isinstance(_properties, Unset):
            properties = UNSET
        else:
            properties = DataSourceProperties.from_dict(_properties)

        def _parse_run_config(data: object) -> KilnAgentRunConfigProperties | McpRunConfigProperties | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                run_config_type_0_type_0 = KilnAgentRunConfigProperties.from_dict(data)

                return run_config_type_0_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                run_config_type_0_type_1 = McpRunConfigProperties.from_dict(data)

                return run_config_type_0_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(KilnAgentRunConfigProperties | McpRunConfigProperties | None | Unset, data)

        run_config = _parse_run_config(d.pop("run_config", UNSET))

        data_source = cls(
            type_=type_,
            properties=properties,
            run_config=run_config,
        )

        data_source.additional_properties = d
        return data_source

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
