# Auto-generated by build_desktop_app.sh. Values are baked in at build time
# from KILN_SENTRY_ENV / KILN_SENTRY_RELEASE so the packaged app reports the
# correct environment and release tag without depending on user-side env vars.
SENTRY_ENV: str | None = None
SENTRY_RELEASE: str | None = None
