"""
Wrapper for OpenAI types to make them compatible with Pydantic.

Pydantic doesn't support Iterable[T] well, so we use List[T] instead for tool_calls,
https://github.com/pydantic/pydantic/issues/9541

Otherwise we are using OpenAI SDK types directly.
"""

from typing import (
    Any,
    Iterable,
    List,
    Literal,
    Optional,
    TypeAlias,
    Union,
)

from openai.types.chat import (
    ChatCompletionContentPartTextParam,
    ChatCompletionDeveloperMessageParam,
    ChatCompletionFunctionMessageParam,
    ChatCompletionMessageToolCallParam,
    ChatCompletionSystemMessageParam,
    ChatCompletionUserMessageParam,
)
from openai.types.chat.chat_completion_assistant_message_param import (
    Audio,
    ContentArrayOfContentPart,
    FunctionCall,
)
from typing_extensions import Required, TypedDict


class ChatCompletionAssistantMessageParamWrapper(TypedDict, total=False):
    """
    Almost exact copy of ChatCompletionAssistantMessageParam, but two changes.

    First change: List[T] instead of Iterable[T] for tool_calls. Addresses pydantic issue.
    https://github.com/pydantic/pydantic/issues/9541

    Second change: Add reasoning_content to the message. A LiteLLM property for reasoning data.
    """

    role: Required[Literal["assistant"]]
    """The role of the messages author, in this case `assistant`."""

    audio: Optional[Audio]
    """Data about a previous audio response from the model.

    [Learn more](https://platform.openai.com/docs/guides/audio).
    """

    content: Union[str, Iterable[ContentArrayOfContentPart], None]
    """The contents of the assistant message.

    Required unless `tool_calls` or `function_call` is specified.
    """

    reasoning_content: Optional[str]
    """The reasoning content of the assistant message. 
    
    A LiteLLM property for reasoning data: https://docs.litellm.ai/docs/reasoning_content
    """

    function_call: Optional[FunctionCall]
    """Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the
    model.
    """

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """

    refusal: Optional[str]
    """The refusal message by the assistant."""

    tool_calls: List[ChatCompletionMessageToolCallParam]
    """The tool calls generated by the model, such as function calls."""

    latency_ms: Optional[int]
    """Time spent waiting on this specific LLM API call in milliseconds."""

    usage: Optional[Any]
    """Token usage for this specific LLM API call.

    The runtime value is a ``kiln_ai.datamodel.usage.Usage`` instance (or
    its dict serialization on a deserialized trace). Typed as ``Any`` to
    avoid an import cycle: ``kiln_ai.datamodel`` eagerly loads ``task_run``,
    which imports from this module, so any direct annotation of ``Usage``
    here would form a cycle that breaks Pydantic's schema build for
    ``TaskRun.trace``.

    Captured per-call (not summed) so downstream consumers can sum across
    every assistant turn in the trace and recover provider-true totals —
    even when multiple inferences happen inside a single
    ``return_on_tool_call=False`` turn (the loop where the model calls a
    tool, the adapter runs it internally, and the model is re-called
    within the same ``call_model`` invocation). Without this field, only
    the last inference's usage shows up on the saved snapshot's
    ``task_run.usage``, and inner-loop inferences are billed by the
    provider but invisible to trace consumers.
    """


class ChatCompletionToolMessageParamWrapper(TypedDict, total=False):
    content: Required[Union[str, Iterable[ChatCompletionContentPartTextParam]]]
    """The contents of the tool message."""

    role: Required[Literal["tool"]]
    """The role of the messages author, in this case `tool`."""

    tool_call_id: Required[str]
    """Tool call that this message is responding to."""

    kiln_task_tool_data: Optional[str]
    """The data for the Kiln task tool that this message is responding to.

    Formatted as `<project_id>:::<tool_id>:::<task_id>:::<run_id>`
    """

    is_error: Optional[bool]
    """Whether this tool message represents an error result."""

    error_message: Optional[str]
    """Human-readable error description when is_error is True."""


ChatCompletionMessageParam: TypeAlias = Union[
    ChatCompletionDeveloperMessageParam,
    ChatCompletionSystemMessageParam,
    ChatCompletionUserMessageParam,
    ChatCompletionAssistantMessageParamWrapper,
    ChatCompletionToolMessageParamWrapper,
    ChatCompletionFunctionMessageParam,
]


KILN_ONLY_MESSAGE_FIELDS: frozenset[str] = frozenset(
    {
        "latency_ms",
        "usage",
        "is_error",
        "error_message",
        "kiln_task_tool_data",
    }
)
"""Per-message fields kept on traces for UI/diagnostics. Providers reject unknown
keys, so these are stripped before sending to LiteLLM. Add new Kiln-only message
fields here when extending the wrappers above."""


def sanitize_messages_for_provider(messages: Iterable[Any]) -> list[Any]:
    """Return a copy of ``messages`` with ``KILN_ONLY_MESSAGE_FIELDS`` removed
    from any dict entries. Non-dict entries (e.g. LiteLLM ``Message`` objects)
    pass through unchanged. The input list and its dicts are not mutated."""
    sanitized: list[Any] = []
    for message in messages:
        # Traces mix TypedDict messages (which may carry kiln-only fields) with
        # LiteLLM Message pydantic objects returned from prior calls (which never
        # do). Only dicts need stripping; pass other types through untouched.
        if isinstance(message, dict):
            sanitized.append(
                {k: v for k, v in message.items() if k not in KILN_ONLY_MESSAGE_FIELDS}
            )
        else:
            sanitized.append(message)
    return sanitized


def trace_has_pending_client_tool_calls(
    trace: list[ChatCompletionMessageParam] | None,
) -> bool:
    """Return True if the trace ends with an assistant message awaiting client tool results.

    Structured-output flows use an internal ``task_response`` tool call; traces that end
    with only those calls are complete from the client's perspective for external tools.
    """
    if not trace:
        return False
    last_msg = trace[-1]
    if last_msg.get("role") != "assistant":
        return False
    tool_calls = last_msg.get("tool_calls") or []
    return any(
        isinstance(tc, dict)
        and (tc.get("function") or {}).get("name") != "task_response"
        for tc in tool_calls
    )
