"""
Wrapper for OpenAI types to make them compatible with Pydantic.

Pydantic doesn't support Iterable[T] well, so we use List[T] instead for every
Iterable[T] field the OpenAI SDK declares: tool_calls, and the list-of-parts form
of content on every role that allows it.
https://github.com/pydantic/pydantic/issues/9541

Pydantic validates an Iterable[T] field into a single-use ValidatorIterator rather
than a list. Serializing reads it, and a read empties it, so a list-valued content
would be written to disk as `content: []` - silently, and permanently. List[T]
materializes at validation time instead, which also makes the message deep-copyable
(a ValidatorIterator cannot be pickled).

The wrappers below exist only to make that substitution; every other field matches
the OpenAI SDK type of the same name, plus the Kiln-only fields in
KILN_ONLY_MESSAGE_FIELDS.
"""

from typing import (
    Annotated,
    Any,
    Iterable,
    List,
    Literal,
    Optional,
    TypeAlias,
    Union,
)

from openai.types.chat import (
    ChatCompletionContentPartParam,
    ChatCompletionContentPartTextParam,
    ChatCompletionFunctionMessageParam,
    ChatCompletionMessageToolCallParam,
)
from openai.types.chat.chat_completion_assistant_message_param import (
    Audio,
    ContentArrayOfContentPart,
    FunctionCall,
)
from pydantic import BeforeValidator, TypeAdapter
from typing_extensions import Required, TypedDict

from kiln_ai.utils.usage import MessageUsage


class ChatCompletionDeveloperMessageParamWrapper(TypedDict, total=False):
    """
    Almost exact copy of ChatCompletionDeveloperMessageParam, with one change:
    List[T] instead of Iterable[T] for content. Addresses pydantic issue.
    https://github.com/pydantic/pydantic/issues/9541
    """

    content: Required[Union[str, List[ChatCompletionContentPartTextParam]]]
    """The contents of the developer message."""

    role: Required[Literal["developer"]]
    """The role of the messages author, in this case `developer`."""

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """


class ChatCompletionSystemMessageParamWrapper(TypedDict, total=False):
    """
    Almost exact copy of ChatCompletionSystemMessageParam, with one change:
    List[T] instead of Iterable[T] for content. Addresses pydantic issue.
    https://github.com/pydantic/pydantic/issues/9541
    """

    content: Required[Union[str, List[ChatCompletionContentPartTextParam]]]
    """The contents of the system message."""

    role: Required[Literal["system"]]
    """The role of the messages author, in this case `system`."""

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """


class ChatCompletionUserMessageParamWrapper(TypedDict, total=False):
    """
    Almost exact copy of ChatCompletionUserMessageParam, with one change:
    List[T] instead of Iterable[T] for content. Addresses pydantic issue.
    https://github.com/pydantic/pydantic/issues/9541

    This is the multimodal message type: its content parts include images, audio
    and files, not only text.
    """

    content: Required[Union[str, List[ChatCompletionContentPartParam]]]
    """The contents of the user message."""

    role: Required[Literal["user"]]
    """The role of the messages author, in this case `user`."""

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """


class ChatCompletionAssistantMessageParamWrapper(TypedDict, total=False):
    """
    Almost exact copy of ChatCompletionAssistantMessageParam, but two changes.

    First change: List[T] instead of Iterable[T] for tool_calls and content. Addresses pydantic issue.
    https://github.com/pydantic/pydantic/issues/9541

    Second change: Add reasoning_content to the message. A LiteLLM property for reasoning data.
    """

    role: Required[Literal["assistant"]]
    """The role of the messages author, in this case `assistant`."""

    audio: Optional[Audio]
    """Data about a previous audio response from the model.

    [Learn more](https://platform.openai.com/docs/guides/audio).
    """

    content: Union[str, List[ContentArrayOfContentPart], None]
    """The contents of the assistant message.

    Required unless `tool_calls` or `function_call` is specified.
    """

    reasoning_content: Optional[str]
    """The reasoning content of the assistant message. 
    
    A LiteLLM property for reasoning data: https://docs.litellm.ai/docs/reasoning_content
    """

    function_call: Optional[FunctionCall]
    """Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the
    model.
    """

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """

    refusal: Optional[str]
    """The refusal message by the assistant."""

    tool_calls: List[ChatCompletionMessageToolCallParam]
    """The tool calls generated by the model, such as function calls."""

    latency_ms: Optional[int]
    """Time spent waiting on this specific LLM API call in milliseconds."""

    usage: Optional[MessageUsage]
    """Token usage and cost for the LLM call that produced this assistant message.

    Set per-call (one record per LLM response, not per logical turn). Stripped
    before sending messages back to providers via KILN_ONLY_MESSAGE_FIELDS.
    Per-call latency lives on the message's `latency_ms` field — MessageUsage
    intentionally does not carry latency.
    """


class ChatCompletionToolMessageParamWrapper(TypedDict, total=False):
    content: Required[Union[str, List[ChatCompletionContentPartTextParam]]]
    """The contents of the tool message."""

    role: Required[Literal["tool"]]
    """The role of the messages author, in this case `tool`."""

    tool_call_id: Required[str]
    """Tool call that this message is responding to."""

    kiln_task_tool_data: Optional[str]
    """The data for the Kiln task tool that this message is responding to.

    Formatted as `<project_id>:::<tool_id>:::<task_id>:::<run_id>`
    """

    is_error: Optional[bool]
    """Whether this tool message represents an error result."""

    error_message: Optional[str]
    """Human-readable error description when is_error is True."""


ChatCompletionMessageParam: TypeAlias = Union[
    ChatCompletionDeveloperMessageParamWrapper,
    ChatCompletionSystemMessageParamWrapper,
    ChatCompletionUserMessageParamWrapper,
    ChatCompletionAssistantMessageParamWrapper,
    ChatCompletionToolMessageParamWrapper,
    ChatCompletionFunctionMessageParam,
]


KILN_ONLY_MESSAGE_FIELDS: frozenset[str] = frozenset(
    {
        "latency_ms",
        "is_error",
        "error_message",
        "kiln_task_tool_data",
        "usage",
    }
)
"""Per-message fields kept on traces for UI/diagnostics. Providers reject unknown
keys, so these are stripped before sending to LiteLLM. Add new Kiln-only message
fields here when extending the wrappers above."""


def sanitize_messages_for_provider(messages: Iterable[Any]) -> list[Any]:
    """Return a copy of ``messages`` with ``KILN_ONLY_MESSAGE_FIELDS`` removed
    from any dict entries. Non-dict entries (e.g. LiteLLM ``Message`` objects)
    pass through unchanged. The input list and its dicts are not mutated."""
    sanitized: list[Any] = []
    for message in messages:
        # Traces mix TypedDict messages (which may carry kiln-only fields) with
        # LiteLLM Message pydantic objects returned from prior calls (which never
        # do). Only dicts need stripping; pass other types through untouched.
        if isinstance(message, dict):
            sanitized.append(
                {k: v for k, v in message.items() if k not in KILN_ONLY_MESSAGE_FIELDS}
            )
        else:
            sanitized.append(message)
    return sanitized


def materialize_lazy_content(trace: Any) -> Any:
    """Normalize a lazily-iterable ``content`` to a list, in front of union validation.

    The wrappers declare ``content`` as ``List[T]``, so a list arrives whole. A caller
    can still hand over any other iterable - a generator, a ``map`` object - and that
    is where pydantic's smart union bites: it tries its members in order, and the
    members whose role does not match still drain the iterator before they fail. By the
    time the matching member runs there is nothing left to read, and the message
    validates to ``content: []`` - silently, with the parts gone. Draining it here,
    once, is what makes that safe.

    Scoped to ``content`` deliberately, and it needs to stay that way. Iterating a
    pydantic model yields its ``(name, value)`` pairs, so a walk over "any iterable
    value" would turn a message's ``usage`` into a list of pairs.

    Returns copies: the caller's own messages are never mutated. Anything that is not
    a list of dicts passes through untouched, for pydantic to reject with its own error.
    """
    if not isinstance(trace, list):
        return trace

    materialized: list[Any] = []
    for message in trace:
        content = message.get("content") if isinstance(message, dict) else None
        if (
            content is not None
            and not isinstance(content, (str, bytes, list, dict))
            and isinstance(content, Iterable)
        ):
            message = {**message, "content": list(content)}
        materialized.append(message)
    return materialized


Trace: TypeAlias = Annotated[
    list[ChatCompletionMessageParam], BeforeValidator(materialize_lazy_content)
]
"""A trace as a pydantic model should declare it.

Use this, not a bare ``list[ChatCompletionMessageParam]``: the validator is what
stops a lazily-iterable ``content`` from being drained to nothing by the union - see
:func:`materialize_lazy_content`.
"""


_trace_adapter: TypeAdapter[list[ChatCompletionMessageParam]] = TypeAdapter(
    list[ChatCompletionMessageParam]
)


def serialize_trace(trace: list[ChatCompletionMessageParam]) -> str:
    """Serialize a trace to the pretty-printed JSON that Kiln stores and displays.

    Not `json.dumps`: a validated trace is not plain data. Pydantic coerces the
    per-message `usage` key to a `MessageUsage` model (both in memory and when a
    TaskRun is loaded back off disk), and the stdlib encoder cannot serialize it.
    For an otherwise-plain trace this returns byte-for-byte what `json.dumps(...,
    indent=2, ensure_ascii=False)` returned, so stored traces render unchanged.
    """
    # warnings=False: every message with a key the wrappers don't declare or a
    # `Usage` in the `usage` slot fails to match a union member and emits a
    # six-line serializer warning - on every message, on every eval-results
    # request. The mismatch is not a defect: pydantic then falls
    # back to duck-typed inference, which is exactly what keeps the output
    # byte-identical to the `json.dumps` this replaced. Silencing it loses no signal
    # a test wouldn't catch first - TestSerializeTrace pins that parity, including
    # the unknown-key and unknown-role cases that rely on the fallback, so a pydantic
    # upgrade that tightened union serialization fails there rather than in a log.
    return _trace_adapter.dump_json(trace, indent=2, warnings=False).decode()


def trace_has_pending_client_tool_calls(
    trace: list[ChatCompletionMessageParam] | None,
) -> bool:
    """Return True if the trace ends with an assistant message awaiting client tool results.

    Structured-output flows use an internal ``task_response`` tool call; traces that end
    with only those calls are complete from the client's perspective for external tools.
    """
    if not trace:
        return False
    last_msg = trace[-1]
    if last_msg.get("role") != "assistant":
        return False
    tool_calls = last_msg.get("tool_calls") or []
    return any(
        isinstance(tc, dict)
        and (tc.get("function") or {}).get("name") != "task_response"
        for tc in tool_calls
    )
