import type { GepaJob } from "$lib/types"

export const DUMMY_GEPA_JOBS: GepaJob[] = [
  {
    v: 1,
    id: "dummy-gepa-job-001",
    path: null,
    created_at: "2026-02-07T13:20:00Z",
    created_by: "sam@kiln.tech",
    name: "Optimize Customer Support Prompt",
    description:
      "Optimizing the customer support prompt to improve tone and accuracy across all evaluators.",
    job_id: "remote-job-abc123",
    token_budget: "medium",
    target_run_config_id: "run-config-001",
    latest_status: "succeeded",
    optimized_prompt:
      "You are a helpful customer support agent for Acme Corp. Your goal is to resolve customer issues quickly and empathetically.\n\nGuidelines:\n- Always greet the customer warmly\n- Acknowledge their frustration before offering solutions\n- Provide step-by-step instructions when troubleshooting\n- If you cannot resolve the issue, escalate to a human agent\n- End every interaction by confirming the customer's issue is resolved\n\nTone: Professional yet warm. Use simple language. Avoid jargon.",
    created_prompt_id: "prompt-optimized-001",
    created_run_config_id: "run-config-optimized-001",
    eval_ids: ["eval-tone-001", "eval-accuracy-002", "eval-helpfulness-003"],
    model_type: "gepa_job",
  },
  {
    v: 1,
    id: "dummy-gepa-job-006",
    path: null,
    created_at: "2026-02-08T08:30:00Z",
    created_by: "sam@kiln.tech",
    name: "Legal Document Analyzer",
    description: "Optimizing legal document analysis for compliance checking.",
    job_id: "remote-job-pqr678",
    token_budget: "heavy",
    target_run_config_id: "run-config-003",
    latest_status: "cancelled",
    optimized_prompt: null,
    created_prompt_id: null,
    created_run_config_id: null,
    eval_ids: [
      "eval-accuracy-002",
      "eval-compliance-005",
      "eval-completeness-006",
    ],
    model_type: "gepa_job",
  },
  {
    v: 1,
    id: "dummy-gepa-job-003",
    path: null,
    created_at: "2026-02-10T16:45:00Z",
    created_by: "alex@kiln.tech",
    name: "Summarization Prompt Tuning",
    description: null,
    job_id: "remote-job-ghi789",
    token_budget: "light",
    target_run_config_id: "run-config-003",
    latest_status: "failed",
    optimized_prompt: null,
    created_prompt_id: null,
    created_run_config_id: null,
    eval_ids: ["eval-conciseness-001"],
    model_type: "gepa_job",
  },
  {
    v: 1,
    id: "dummy-gepa-job-002",
    path: null,
    created_at: "2026-02-11T09:15:00Z",
    created_by: "sam@kiln.tech",
    name: "Code Review Assistant v2",
    description: "Second iteration of the code review assistant prompt.",
    job_id: "remote-job-def456",
    token_budget: "heavy",
    target_run_config_id: "run-config-002",
    latest_status: "running",
    optimized_prompt: null,
    created_prompt_id: null,
    created_run_config_id: null,
    eval_ids: ["eval-code-quality-001", "eval-security-002"],
    model_type: "gepa_job",
  },
  {
    v: 1,
    id: "dummy-gepa-job-005",
    path: null,
    created_at: "2026-02-12T14:30:00Z",
    created_by: "alex@kiln.tech",
    name: "Chat Assistant Warmth Tuning",
    description:
      "Tuning the chat assistant prompt for warmer, more conversational tone.",
    job_id: "remote-job-mno345",
    token_budget: "light",
    target_run_config_id: "run-config-002",
    latest_status: "pending",
    optimized_prompt: null,
    created_prompt_id: null,
    created_run_config_id: null,
    eval_ids: ["eval-tone-001", "eval-engagement-004"],
    model_type: "gepa_job",
  },
]
