[post-create]
copy_user_settigns = "cp ./../../.config/wt/user_settings.sh ./config/wt && exit 0"
deps = "config/wt/install_deps.sh"
claude = "utils/setup_claude.sh"

[pre-remove]
session = "zellij delete-session {{ branch | sanitize }} 2>/dev/null || true"
