name: Debug Detector

on:
  push:
    branches: [main]
  pull_request:

jobs:
  developer-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Search for leftover debug content
        run: |
          set +e
          found=0

          echo "Checking for python print statements"
          prints=$(grep -nR --include='*.py' --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=.git --exclude-dir=.github --exclude-dir=build --exclude-dir=dist --exclude-dir=.svelte-kit -e 'print(' . || true)
          if [ -n "$prints" ]; then
            echo "$prints"
            found=1
          fi

          echo "Checking for TODO or FIXME"
          notes=$(grep -nR --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=.git --exclude-dir=.github --exclude-dir=build --exclude-dir=dist --exclude-dir=.svelte-kit -e 'TODO' -e 'FIXME' . || true)
          if [ -n "$notes" ]; then
            echo "$notes"
            found=1
          fi

          if [ "$found" -ne 0 ]; then
            echo "Developer content found" >&2
            exit 1
          else
            echo "No developer content found"
          fi
