# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# We use "ruff" for linting and formatting

name: Format and Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  format_and_lint:
    name: Format and Lint Python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download misspell tool
        run: |
          wget https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz
          tar -xzf misspell_0.3.4_linux_64bit.tar.gz
          chmod +x misspell

      - name: Run misspell
        run: ./misspell -error .

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv tool install ruff

      - name: Lint with ruff
        run: |
          uvx ruff check

      - name: Format with ruff
        run: |
          uvx ruff format --check .
