name: Build Signed Windows Release

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      # Use 3.12 - 3.13 not working yet (Numpy verion too old)
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # Use GH python version (includes TK/TCL)
      - name: Set up Python using GH python version
        run: uv venv --python 3.12 --python-preference only-system

      - name: Install the project, without pyinstaller dev dependency as we'll install it manually
        run: uv sync --no-group dev

      - name: Build Desktop App including pyinstaller bootloader
        run: uv run bash ./app/desktop/build_desktop_app.sh --build-bootloader

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: kiln-desktop-windows-signed-installer
          path: ./app/desktop/build/dist/*
